# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
